[package]
name = "zenity"
version = "1.0.4"
authors = ["Arteii <ben.arteii@proton.me>"]
edition = "2021"
license-file = "LICENSE.md"
readme = "README.md"
categories = ["command-line-utilities", "command-line-interface"]


description = "easy to use cli animation lib (Yet Another Spinner Lib ) 81+ predefined"
repository = "https://github.com/Arteiii/zenity"
keywords = ["console", "animations", "cli", "spinner", "loading"]
homepage = "https://arteiii.github.io"


[dependencies]
crossterm = "0.27.0"

[dev-dependencies]
unicode-icons = "1.0.1"
