name: Compile Rust Examples and Upload to Release

on:
  push:
    branches:
      - '*'

jobs:
  build_windows:
    name: Compile Examples for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust for Windows
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Compile Examples for Windows
        run: cargo build --examples --release

      - name: Move Windows Executables
        run: |
          mkdir -p windows
          mv target/release/examples/main.exe windows/
          mv target/release/examples/basic.exe windows/
          mv target/release/examples/all.exe windows/

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: examples-windows
          path: windows/

  build_unix:
    name: Compile Examples for Unix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust for Unix
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Compile Examples for Unix
        run: cargo build --examples --release

      - name: Move Unix Executables
        run: |
          mkdir -p unix
          mv target/release/examples/main unix/
          mv target/release/examples/basic unix/
          mv target/release/examples/all unix/

      - name: Upload Unix Artifact
        uses: actions/upload-artifact@v2
        with:
          name: examples-unix
          path: unix/
